### ISSUE TITLE
Does not work for RGB images

### ISSUE THREAD

**Issue by Emanuele97x** [qgpmztmf/Stationary_Wavelet_Transform_PyTorch#1]
Hi! Thanks a lot for your work, I was wondering why the provided code does not work for RGB images and whether is there a simple workaround to adopt it to multi-channel images.

Best,

Emanuele

**Comment by qgpmztmf** [comment]
> Hi! Thanks a lot for your work, I was wondering why the provided code does not work for RGB images and whether is there a simple workaround to adopt it to multi-channel images.
> 
> Best,
> 
> Emanuele

Sorry for my late reply. Generally, wavelet transform can only be applied to single-channel images. However, you could attempt to apply wavelet transform to each channel of an RGB image and then combine them.
